{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.zekerzhayard",
    "module": "ForgeWrapper",
    "version": "1.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeWrapper-1.5.7.jar",
          "url": "ForgeWrapper-1.5.7.jar",
          "size": 34910,
          "sha512": "5ac801b05d8ee30518885d89e3cf4ffd8e3024ffaf1904bc42ddd4485a2b1ddda4d8eec55cf0341a2c8b4d62d81019c58e415b8bc820e8773e2098debd485dc9",
          "sha256": "2e4b7af5df7c8c8d36737fceed505fe08654db73d7ca24c1341f499dbe2693ae",
          "sha1": "155ac9f4e5f65288eaacae19025ac4d9da1f0ef2",
          "md5": "3f5a665e47e81102b6aba68ddb04c917"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ForgeWrapper",
          "module": "common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "ForgeWrapper",
          "module": "legacy",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "ForgeWrapper",
          "module": "jigsaw",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "ForgeWrapper-1.5.7.jar",
          "url": "ForgeWrapper-1.5.7.jar",
          "size": 34910,
          "sha512": "5ac801b05d8ee30518885d89e3cf4ffd8e3024ffaf1904bc42ddd4485a2b1ddda4d8eec55cf0341a2c8b4d62d81019c58e415b8bc820e8773e2098debd485dc9",
          "sha256": "2e4b7af5df7c8c8d36737fceed505fe08654db73d7ca24c1341f499dbe2693ae",
          "sha1": "155ac9f4e5f65288eaacae19025ac4d9da1f0ef2",
          "md5": "3f5a665e47e81102b6aba68ddb04c917"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeWrapper-1.5.7-sources.jar",
          "url": "ForgeWrapper-1.5.7-sources.jar",
          "size": 10562,
          "sha512": "a90df4495787bf0e3aaf0a9511e454d65cd3bb9b20f9cbd1db6ec6c4a04a0d79627b1189542b5f7b914e308f24c37905b27306f38419aa4ee8ebee3d4b8eef16",
          "sha256": "e463cbafa2701f33c7cbe5bf75a32c78d470bc03e15e8fccf861842cdfce0a8a",
          "sha1": "ba17f0f4330527a020d4868d950e18bfc3c6f2d2",
          "md5": "91a6fc2f499ef6012ada3d97bb19834d"
        }
      ]
    }
  ]
}
