{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.zekerzhayard",
    "module": "ForgeWrapper",
    "version": "1.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeWrapper-1.5.6.jar",
          "url": "ForgeWrapper-1.5.6.jar",
          "size": 34715,
          "sha512": "ccdba2a2aaf55e651701775096b0ffabb7fc95ade4063785756bf82e563e6430ef5e72c7cf78c741f61eec83e506189847fc34242a7b63d64835babb2328f8ef",
          "sha256": "2ecf1d98fe8d8051802fa42e5bd61153d374b87c2dcf9499cbe1d0c1a84df279",
          "sha1": "b38d28e8b7fde13b1bc0db946a2da6760fecf98d",
          "md5": "22ddbab2bbf66451afe0a47b8642fbbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ForgeWrapper",
          "module": "common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "ForgeWrapper",
          "module": "legacy",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "ForgeWrapper",
          "module": "jigsaw",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "ForgeWrapper-1.5.6.jar",
          "url": "ForgeWrapper-1.5.6.jar",
          "size": 34715,
          "sha512": "ccdba2a2aaf55e651701775096b0ffabb7fc95ade4063785756bf82e563e6430ef5e72c7cf78c741f61eec83e506189847fc34242a7b63d64835babb2328f8ef",
          "sha256": "2ecf1d98fe8d8051802fa42e5bd61153d374b87c2dcf9499cbe1d0c1a84df279",
          "sha1": "b38d28e8b7fde13b1bc0db946a2da6760fecf98d",
          "md5": "22ddbab2bbf66451afe0a47b8642fbbe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeWrapper-1.5.6-sources.jar",
          "url": "ForgeWrapper-1.5.6-sources.jar",
          "size": 10318,
          "sha512": "26f37ab9ada355cdf25ff5763fcdd9bc3d2faac2c0d229516d2f4697ccfcd9c63d50cb6082bc77c0426aecb414b18b7ef14b3e135d6fb789496d39a0f9cabe1b",
          "sha256": "7695f5cd50a72abd3854d9f1b7b538165d03c027f4cb125fed3f8d846f8cfcc1",
          "sha1": "87589ff603c0b3342484981135dade0de415d701",
          "md5": "28070b211491b949d280440d2864e0c2"
        }
      ]
    }
  ]
}
