{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.zekerzhayard",
    "module": "ForgeWrapper",
    "version": "mmc3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeWrapper-mmc3.jar",
          "url": "ForgeWrapper-mmc3.jar",
          "size": 34472,
          "sha512": "08a64e02a625c14e554f3945128e7a4a67400b0c0212a33c058e7846d579c7c6e23d5033fa2c16988466f9b26bac9d92816476686e6709c37357e7194a695486",
          "sha256": "b2770e7c10b2b58640fb91f941557a3e7e4dd3760b97bd8f03c2ddc0cbd263f4",
          "sha1": "0bd8b4e13fc77d506157976c6846b867392e5113",
          "md5": "a7f75000c7911b7fb27debdf54d28601"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ForgeWrapper",
          "module": "common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "ForgeWrapper",
          "module": "legacy",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "ForgeWrapper",
          "module": "jigsaw",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "ForgeWrapper-mmc3.jar",
          "url": "ForgeWrapper-mmc3.jar",
          "size": 34472,
          "sha512": "08a64e02a625c14e554f3945128e7a4a67400b0c0212a33c058e7846d579c7c6e23d5033fa2c16988466f9b26bac9d92816476686e6709c37357e7194a695486",
          "sha256": "b2770e7c10b2b58640fb91f941557a3e7e4dd3760b97bd8f03c2ddc0cbd263f4",
          "sha1": "0bd8b4e13fc77d506157976c6846b867392e5113",
          "md5": "a7f75000c7911b7fb27debdf54d28601"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeWrapper-mmc3-sources.jar",
          "url": "ForgeWrapper-mmc3-sources.jar",
          "size": 10418,
          "sha512": "5851dd05498bd42a4cfb21cdd76a870dc0e593f12f75a0b4cc067096557df64f702caaf84b637e00f2cdd27489f7505bd40939ea1b33eec23927385b98dd809f",
          "sha256": "2edfd171c53b8277c1c170762543c5907937cc6b85356ca7cf598b790428f153",
          "sha1": "bed34924add768da35eceee0ec32fdeca2542331",
          "md5": "551fd123aeba3d15cbce9d7b52bca469"
        }
      ]
    }
  ]
}
